import { supabase } from "@/integrations/supabase/client";
import type { Game, Player, GameStatus } from "@/types/game";

export const gameService = {
  async createGame(hostId: string, name: string, eliminationMethod: string, safeZones?: string, safeTimes?: string): Promise<Game> {
    const { data, error } = await supabase
      .from('games')
      .insert({
        host_id: hostId,
        name,
        elimination_method: eliminationMethod,
        safe_zones: safeZones || null,
        safe_times: safeTimes || null,
        code: '', // Will be auto-generated by trigger
      })
      .select()
      .single();

    if (error) throw error;
    return data as Game;
  },

  async getGameByCode(code: string): Promise<Game | null> {
    const { data, error } = await supabase
      .from('games')
      .select('*')
      .eq('code', code.toUpperCase())
      .single();

    if (error) return null;
    return data as Game;
  },

  async getGameById(id: string): Promise<Game | null> {
    const { data, error } = await supabase
      .from('games')
      .select('*')
      .eq('id', id)
      .single();

    if (error) return null;
    return data as Game;
  },

  async addPlayer(gameId: string, name: string): Promise<Player> {
    const { data, error } = await supabase
      .from('players')
      .insert({
        game_id: gameId,
        name,
      })
      .select()
      .single();

    if (error) throw error;
    return data as Player;
  },

  async getPlayers(gameId: string): Promise<Player[]> {
    const { data, error } = await supabase
      .from('players')
      .select('*')
      .eq('game_id', gameId)
      .order('created_at', { ascending: true });

    if (error) throw error;
    return data as Player[];
  },

  async removePlayer(playerId: string): Promise<void> {
    const { error } = await supabase
      .from('players')
      .delete()
      .eq('id', playerId);

    if (error) throw error;
  },

  async startGame(gameId: string): Promise<void> {
    // Get all players
    const players = await this.getPlayers(gameId);
    if (players.length < 2) throw new Error('Need at least 2 players');

    // Shuffle players to create random order
    const shuffled = [...players].sort(() => Math.random() - 0.5);

    // Assign targets in a closed loop
    for (let i = 0; i < shuffled.length; i++) {
      const targetIndex = (i + 1) % shuffled.length;
      await supabase
        .from('players')
        .update({ 
          target_id: shuffled[targetIndex].id,
          reveal_order: i + 1
        })
        .eq('id', shuffled[i].id);
    }

    // Update game status
    const { error } = await supabase
      .from('games')
      .update({ 
        status: 'active' as GameStatus,
        started_at: new Date().toISOString()
      })
      .eq('id', gameId);

    if (error) throw error;
  },

  async eliminatePlayer(gameId: string, eliminatedId: string): Promise<void> {
    // Get the eliminated player
    const { data: eliminated } = await supabase
      .from('players')
      .select('*, target_id')
      .eq('id', eliminatedId)
      .single();

    if (!eliminated) throw new Error('Player not found');

    // Find who was hunting the eliminated player
    const { data: hunter } = await supabase
      .from('players')
      .select('*')
      .eq('target_id', eliminatedId)
      .eq('is_alive', true)
      .single();

    // Mark player as eliminated
    await supabase
      .from('players')
      .update({ 
        is_alive: false,
        eliminated_at: new Date().toISOString()
      })
      .eq('id', eliminatedId);

    // Record the elimination
    if (hunter) {
      await supabase
        .from('eliminations')
        .insert({
          game_id: gameId,
          eliminator_id: hunter.id,
          eliminated_id: eliminatedId
        });

      // Reassign hunter's target
      await supabase
        .from('players')
        .update({ target_id: (eliminated as Player).target_id })
        .eq('id', hunter.id);
    }

    // Check if game is over
    const { data: alivePlayers } = await supabase
      .from('players')
      .select('id')
      .eq('game_id', gameId)
      .eq('is_alive', true);

    if (alivePlayers && alivePlayers.length === 1) {
      await supabase
        .from('games')
        .update({ 
          status: 'ended' as GameStatus,
          winner_id: alivePlayers[0].id,
          ended_at: new Date().toISOString()
        })
        .eq('id', gameId);
    }
  },

  async pauseGame(gameId: string): Promise<void> {
    const { error } = await supabase
      .from('games')
      .update({ status: 'paused' as GameStatus })
      .eq('id', gameId);

    if (error) throw error;
  },

  async resumeGame(gameId: string): Promise<void> {
    const { error } = await supabase
      .from('games')
      .update({ status: 'active' as GameStatus })
      .eq('id', gameId);

    if (error) throw error;
  },

  async endGame(gameId: string): Promise<void> {
    const { error } = await supabase
      .from('games')
      .update({ 
        status: 'ended' as GameStatus,
        ended_at: new Date().toISOString()
      })
      .eq('id', gameId);

    if (error) throw error;
  },

  async getHostGames(hostId: string): Promise<Game[]> {
    const { data, error } = await supabase
      .from('games')
      .select('*')
      .eq('host_id', hostId)
      .order('created_at', { ascending: false });

    if (error) throw error;
    return data as Game[];
  }
};
